mru_transform/sensors:
 - name: phins
   topics: { position: 'project11/nav/phins/position', orientation: 'project11/nav/phins/orientation', velocity: 'project11/nav/phins/velocity'}
 - name: gps
   topics: { position: 'project11/nav/oem/position', orientation: 'project11/nav/oem/orientation', velocity: 'project11/nav/oem/velocity'}
 - name: ais
   topics: { position: 'sensors/ais/fix', orientation: 'sensors/ais/heading', velocity: 'sensors/ais/vel'}

helm_manager/output_type: 'helm'
helm_manager/max_yaw_speed: 1.0
helm_manager/max_speed: 6.0


udp_bridge:
  maxPacketSize: 1450
  remotes:
    operator:
      connections:
        default:
          host: salmondr
          topics:
            nav_orientation: {source: project11/nav/phins/orientation, period: .5}
            nav_position: {source: project11/nav/phins/position, period: .5}
            nav_velocity: {source: project11/nav/phins/velocity, period: .5}
            sensors_ais_contact: {source: sensors/ais/contacts}
            sensors_ais_fix: {source: sensors/ais/fix, period: .5}
            sensors_ais_heading: {source: sensors/ais/heading, period: .5}
            sensors_ais_vel: {source: sensors/ais/vel, period: .5}
            # diagnostics: {source: dev/null}
            usbl_raw_audio: {source: usbl_raw/audio}
            usbl_raw_audio_info: {source: usbl_raw/audio_info}
            usbl_modem_raw: {source: usbl_modem/raw}
            par_sensor: {source: /project11/drix_8/sensors/par/data}
        wifi:
          host: salmondw
          port: 4200
          maximumBytesPerSecond: 500000
          topics:
            nav_orientation: {source: project11/nav/phins/orientation, period: .5}
            nav_position: {source: project11/nav/phins/position, period: .5}
            nav_velocity: {source: project11/nav/phins/velocity, period: .5}
            platforms: {source: /project11/platforms}
            project11_display: {source: project11/display}
            project11_heartbeat: {source: project11/heartbeat}
            project11_status_mission_manager: {source: project11/status/mission_manager}
            project11_response: {source: project11/response}
            odom: {source: odom}
            sensors_ais_contact: {source: sensors/ais/contacts}
            sensors_ais_fix: {source: sensors/ais/fix, period: .5}
            sensors_ais_heading: {source: sensors/ais/heading, period: .5}
            sensors_ais_vel: {source: sensors/ais/vel, period: .5}
            tf: {source: /tf}
            tf_static: {source: /tf_static}
            nav_visualization_markers: {source: navigator/visualization_markers}
            par_sensor: {source: /project11/drix_8/sensors/par/data}
        vpn:
          host: salmondv
          port: 4200
          maximumBytesPerSecond: 200000
          topics:
            nav_orientation: {source: project11/nav/phins/orientation, period: .5}
            nav_position: {source: project11/nav/phins/position, period: .5}
            nav_velocity: {source: project11/nav/phins/velocity, period: .5}
            platforms: {source: /project11/platforms}
            project11_display: {source: project11/display}
            project11_heartbeat: {source: project11/heartbeat}
            project11_status_mission_manager: {source: project11/status/mission_manager}
            project11_response: {source: project11/response}
            odom: {source: odom}
            sensors_ais_contact: {source: sensors/ais/contacts}
            sensors_ais_fix: {source: sensors/ais/fix, period: .5}
            sensors_ais_heading: {source: sensors/ais/heading, period: .5}
            sensors_ais_vel: {source: sensors/ais/vel, period: .5}
            tf: {source: /tf}
            tf_static: {source: /tf_static}
            nav_visualization_markers: {source: navigator/visualization_markers}
            par_sensor: {source: /project11/drix_8/sensors/par/data}


s57_grids:
  robot:
    minimum_depth: 1.0
    maximum_caution_depth: 5.0
    overhead_clearance: 5.0
    minimum_speed: 0.01
    maximum_speed: 6.0

  grids:
    - name: global
      resolution: 25.0
      length: 175000.0
      period: 30.0
    - name: area
      resolution: 6.0
      length: 15000.0
      period: 30.0
    - name: local
      resolution: 3.0
      length: 5000.0
      period: 1.0
