mru_transform/sensors:
 - name: phins
   topics: { position: 'project11/nav/phins/position', orientation: 'project11/nav/phins/orientation', velocity: 'project11/nav/phins/velocity'}
 - name: gps
   topics: { position: 'project11/nav/oem/position', orientation: 'project11/nav/oem/orientation', velocity: 'project11/nav/oem/velocity'}
 - name: ais
   topics: { position: 'project11/nav/ais/position', orientation: 'project11/nav/ais/orientation', velocity: 'project11/nav/ais/velocity'}

udp_bridge:
  maxPacketSize: 1450
  remotes:
    operator:
      connections:
        default:
          topics:
            nav_orientation: {source: project11/nav/phins/orientation, period: .5}
            nav_position: {source: project11/nav/phins/position, period: .5}
            nav_velocity: {source: project11/nav/phins/velocity, period: .5}
            sensors_ais_contact: {source: sensors/ais/contacts}
            diagnostics: {source: ''}
            tf: {source: ''}
            tf_static: {source: ''}
            usbl_raw_audio: {source: usbl_raw/audio}
            usbl_raw_audio_info: {source: usbl_raw/audio_info}
            usbl_modem_raw: {source: usbl_modem/raw}
        vpn:
          host: robonucdv
          port: 4200
          maximumBytesPerSecond: 200000
          topics:
            nav_orientation: {source: project11/nav/phins/orientation, period: .5}
            nav_position: {source: project11/nav/phins/position, period: .5}
            nav_velocity: {source: project11/nav/phins/velocity, period: .5}
            platforms: {source: /project11/platforms}
            project11_display: {source: project11/display}
            project11_heartbeat: {source: project11/heartbeat}
            project11_status_mission_manager: {source: project11/status/mission_manager}
            project11_response: {source: project11/response}
            odom: {source: project11/odom}

project11/platforms/drix_8:
  robot_description: project11/drix_8/robot_description
  namespace: project11/drix_8
  width: 0.85
  length: 7.7
  reference_x: 0.65
  nav_sources:
    phins:
      position_topic: /project11/drix_8/project11/nav/phins/position
      orientation_topic: /project11/drix_8/project11/nav/phins/orientation
      velocity_topic: /project11/drix_8/project11/nav/phins/velocity
  color:
    red: 1.0
    green: 0.0
    blue: 0.0

          
s57_grids:
  map_frame: project11/drix_8/map

  robot:
    frame_id: project11/drix_8/base_link
    minimum_depth: 1.0
    maximum_caution_depth: 5.0
    overhead_clearance: 5.0
    minimum_speed: 0.01
    maximum_speed: 6.0

  grids:
    - name: global
      resolution: 25.0
      length: 175000.0
      period: 30.0
    - name: area
      resolution: 6.0
      length: 15000.0
      period: 30.0
    - name: local
      resolution: 3.0
      length: 5000.0
      period: 1.0
