mru_transform/sensors:
 - name: phins
   topics: { position: 'project11/nav/phins/position', orientation: 'project11/nav/phins/orientation', velocity: 'project11/nav/phins/velocity'}
 - name: gps
   topics: { position: 'project11/nav/oem/position', orientation: 'project11/nav/oem/orientation', velocity: 'project11/nav/oem/velocity'}
 - name: ais
   topics: { position: 'project11/nav/ais/position', orientation: 'project11/nav/ais/orientation', velocity: 'project11/nav/ais/velocity'}

udp_bridge/remotes:
  operator:
    connections:
      default:
        topics:
          sensors_ais_contact: {source: project11/ais/contact}
          diagnostics: {source: ''}
          tf: {source: ''}
          tf_static: {source: ''}
          usbl_raw_audio: {source: usbl_raw/audio}
          usbl_raw_audio_info: {source: usbl_raw/audio_info}
          usbl_modem_raw: {source: usbl_modem/raw}
          