mru_transform/sensors:
 - name: active
   topics: { position: 'project11/nav/position', orientation: 'project11/nav/orientation', velocity: 'project11/nav/velocity'}

udp_bridge:
  maxPacketSize: 1450
  remotes:
    robot:
      connections:
        default:
          port: 4201  # Teltonika would not forward 4200, but 4201 works.
          topics:
            project11_command: {source: /project11/drix_8/project11/command}
            piloting_mode_manual_helm: {source: /project11/drix_8/project11/piloting_mode/manual/helm}
        vpn:
          host: echodv
          port: 4201  # Teltonika would not forward 4200, but 4201 works.
          topics:
            project11_command: {source: /project11/drix_8/project11/command}
            piloting_mode_manual_helm: {source: /project11/drix_8/project11/piloting_mode/manual/helm}

# project11/platforms/drix_8:
#   robot_description: project11/drix_8/robot_description
#   namespace: project11/drix_8
#   width: 0.85
#   length: 7.7
#   reference_x: 0.65
#   nav_sources:
#     combined:
#       position_topic: /project11/drix_8/project11/nav/position
#       orientation_topic: /project11/drix_8/project11/nav/orientation
#       velocity_topic: /project11/drix_8/project11/nav/velocity