mru_transform/sensors:
 - name: phins
   topics: { position: 'nav/phins/position', orientation: 'nav/phins//orientation', velocity: 'nav/phins/velocity'}
 - name: gps
   topics: { position: 'nav/oem/position', orientation: 'nav/oem/orientation', velocity: 'nav/oem/velocity'}
