udp_bridge/remotes:
  operator:
    connections:
      default:
        topics:
          # usbl_2001_position: {source: usbl_ranger/positions/2001}
          usbl_2509_position: {source: usbl_ranger/positions/2509}
          usbl_2712_position: {source: usbl_ranger/positions/2712}
          mesobot_heartbeat: {source: /project11/mesobot/project11/heartbeat}
          mesobot_position: {source: /project11/mesobot/nav/position}
          mesobot_heading: {source: /project11/mesobot/heading}
          mesobot_depth: {source: /project11/mesobot/depth}
          mesobot_battery: {source: /project11/mesobot/battery}
          mesobot_radiometer: {source: /project11/mesobot/radiometer}
          mesobot_ctd_c: {source: /project11/mesobot/ctd/c}
          mesobot_ctd_t: {source: /project11/mesobot/ctd/t}
          mesobot_ctd_d: {source: /project11/mesobot/ctd/d}