robot:
  max_velocity:
    linear/x: 12.0

  default_velocity:
    linear/x: 8.0

  turn_radius: 20.0

  footprint: [[4.21, 0], [0, 0.41], [0, -0.41], [-0.7, 0.41], [-0.7, 0.41], [-1.22, 0.4], [-1.22, -0.4], [-3.5, 2.1], [-3.5, -2.1]]


TaskToTwistWorkflow/path_follower:
  pid:
    Kp: 1.0
    Ki: 0.45
    Kd: 0.4

TaskToTwistWorkflow/hover:
  maximum_distance: 30.0
  minimum_distance: 15.0
  maximum_speed: 3.0

grids:
  static:
    chart_global: s57_grids/grids/global
    chart_area: s57_grids/grids/area
    chart_local: s57_grids/grids/local
