robot:
  max_velocity:
    linear/x: 12.0

  default_velocity:
    linear/x: 8.0

  turn_radius: 20.0

TaskToTwistWorkflow/path_follower:
  pid:
    Kp: 1.0
    Ki: 0.45
    Kd: 0.4

grids:
  static:
    chart_global: s57_grids/grids/global
    chart_area: s57_grids/grids/area
    chart_local: s57_grids/grids/local
