udp_bridge/remotes:
    operator:
        topics:
          usbl_5501_position: {source: usbl_ranger/positions/5501}
          usbl_2411_position: {source: usbl_ranger/positions/2411}
          nui_position: {source: /project11/nui/nav/position}
          nui_telegrams: {source: /project11/drix_8/usbl/telegrams}
